services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=adi1010'
      - 'MYSQL_ROOT_PASSWORD=adi1010'
      - 'MYSQL_USER=root'
    ports:
      - '3307:3306'
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-container
    ports:
      - "8082:8080"
    depends_on:
      - mysql-db
    environment:
      MYSQL_URL: jdbc:mysql://mysql-container:3306/inventory?autoReconnect=true&useSSL=false
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root